name: bitcoin_ticker
description: Application that provides prices for different bitcoins.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-133.2.beta <3.0.0"

dependencies:
  cupertino_icons: any
  dio: any
  flutter:
    sdk: flutter
  get: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter:
  uses-material-design: true
