name: movieapp
description: A Movie App based on clean architecture design pattern and cool
  animation with scalablity.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  equatable: ^1.2.4
  http: ^0.12.2
  dartz: ^0.9.1
  get_it: ^4.0.4
  pedantic: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: null

flutter:
  uses-material-design: true
