name: chatroom
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-133.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  flutter_signin_button: ^1.1.0
  google_sign_in: ^4.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  import_sorter: ^4.4.1
  lint: ^1.5.1

flutter:
  uses-material-design: true
