name: podder
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^3.0.10
  flutter_sound: ^1.5.1
  get: 3.21.2
  http: ^0.12.0+2
  provider: ^3.1.0+1
  webfeed: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/haiku.mp3
